export { Bridge, DEFAULT_LIMITS, RULE } from './core.ts';
export { ObservationStore } from './store.ts';
export { commandDigest, immutableResult, resultBytes, resultDeliveryBytes } from './results.ts';
export { NerveletError, serializeError } from './util.ts';
export type { ErrorDetails, SerializedError } from './util.ts';
export { serve, request } from './ipc.ts';
export { createHandlers, toolResult } from './handlers.ts';
export type * from './handlers.ts';
export { Supervisor } from './supervisor.ts';
export { settleEmergency } from './attention.ts';
export type { AttentionTurn } from './attention.ts';
export type * from './supervisor.ts';
export { ChangeSignal } from './changes.ts';
export { instructions, reminder, identityInstructions } from './instructions.ts';
export { immutableProfile } from './profile.ts';
export { stepSchema, waitSchema, waitSchemaFor, waitInstructionsFor, DIALECT } from './schemas.ts';
export type { BridgeOptions } from './core.ts';
export type * from './types.ts';
import type { Config } from './types.ts';
export const defineConfig = (config: Config): Config => config;
